// Default workout program (editable). Stored in localStorage after first load.
// Each exercise has bilingual name/notes, target sets, reps, and a muscle group
// used to render the anatomy illustration. Users can override an `img` (URL/GIF).

const DEFAULT_PROGRAM = {
  version: 4,
  days: [
    {
      id: "upperA",
      icon: "🏋️",
      name: { bg: "Ден 1: Горна А", en: "Day 1: Upper A" },
      focus: {
        bg: "Фокус: Гърди и хоризонтално дърпане",
        en: "Focus: Chest & horizontal pull",
      },
      exercises: [
        {
          id: "u1e1",
          muscle: "chest",
          exdb: "Incline_Dumbbell_Press",
          name: { bg: "Избутване от полулег", en: "Incline Dumbbell Press" },
          sets: 4,
          reps: "8–10",
          notes: { bg: "Пейка на 30°, с тежките дъмбели.", en: "Bench at 30°, heavy dumbbells." },
          steps: {
            bg: [
              "Нагласи пейката на 30° и седни с дъмбел във всяка ръка върху бедрата.",
              "Легни назад, като изведеш дъмбелите до нивото на раменете, длани напред.",
              "Издишай и изтласкай дъмбелите нагоре, докато ръцете почти се изпънат, без да ги удряш.",
              "Спусни бавно (2–3 сек) до усещане за разтягане в горната част на гърдите и повтори.",
            ],
            en: [
              "Set the bench to 30° and sit with a dumbbell on each thigh.",
              "Lie back, bringing the dumbbells to shoulder level, palms facing forward.",
              "Exhale and press the dumbbells up until arms are nearly straight, without clanking them.",
              "Lower slowly (2–3 s) to a stretch in the upper chest, then repeat.",
            ],
          },
          img: "",
        },
        {
          id: "u1e2",
          muscle: "back",
          exdb: "One-Arm_Dumbbell_Row",
          name: { bg: "Гребане с дъмбел (с опора)", en: "Single-Arm Dumbbell Row" },
          sets: 4,
          reps: "8–10",
          notes: { bg: "Опора с коляно на пейката.", en: "Knee supported on the bench." },
          steps: {
            bg: [
              "Постави едно коляно и същата ръка на пейката, гърбът успореден на пода.",
              "Хвани дъмбела с другата ръка, рамото отпуснато надолу.",
              "Дръпни дъмбела към кръста, като водиш с лакътя и стискаш плешката.",
              "Спусни контролирано до пълно разтягане, повтори, после смени ръката.",
            ],
            en: [
              "Place one knee and the same-side hand on the bench, back parallel to the floor.",
              "Grab the dumbbell with the other hand, shoulder relaxed down.",
              "Pull the dumbbell to your waist, leading with the elbow and squeezing the shoulder blade.",
              "Lower under control to a full stretch, repeat, then switch sides.",
            ],
          },
          img: "",
        },
        {
          id: "u1e3",
          muscle: "shoulders",
          exdb: "Side_Lateral_Raise",
          name: { bg: "Вертикално разперване встрани", en: "Lateral Raise" },
          sets: 4,
          reps: "12–15",
          notes: { bg: "За средно рамо (10 кг дъмбели).", en: "For side delts (10 kg dumbbells)." },
          steps: {
            bg: [
              "Застани прав, дъмбели до тялото, лактите леко свити.",
              "Повдигни ръцете встрани до нивото на раменете, без да вдигаш трапеца.",
              "Задръж за кратко горе — китките не по-високо от лактите.",
              "Спусни бавно и контролирано, без да люлееш тялото.",
            ],
            en: [
              "Stand tall, dumbbells at your sides, elbows slightly bent.",
              "Raise the arms out to the sides up to shoulder height, without shrugging.",
              "Pause briefly at the top — wrists no higher than the elbows.",
              "Lower slowly and controlled, without swinging the body.",
            ],
          },
          img: "",
        },
        {
          id: "u1e4",
          muscle: "chest",
          exdb: "Dumbbell_Flyes",
          name: { bg: "Флайс от хоризонтален лег", en: "Flat Dumbbell Fly" },
          sets: 3,
          reps: "12–15",
          notes: {
            bg: "По-широка дъга за максимално разтягане на гърдите.",
            en: "Wide arc for maximum chest stretch.",
          },
          steps: {
            bg: [
              "Легни по гръб на хоризонтална пейка, дъмбели изпънати над гърдите, длани една срещу друга.",
              "С леко свити лакти спускай ръцете встрани по широка дъга.",
              "Спри при усещане за разтягане на гърдите (на нивото на пейката).",
              "Върни по същата дъга, като стискаш гърдите, без да блъскаш дъмбелите.",
            ],
            en: [
              "Lie on a flat bench, dumbbells extended over the chest, palms facing each other.",
              "With elbows slightly bent, lower the arms out to the sides in a wide arc.",
              "Stop when you feel a chest stretch (around bench level).",
              "Return along the same arc, squeezing the chest, without clashing the dumbbells.",
            ],
          },
          img: "",
        },
        {
          id: "u1e5",
          muscle: "biceps",
          exdb: "Incline_Dumbbell_Curl",
          name: { bg: "Бицепсово сгъване от наклон", en: "Incline Dumbbell Curl" },
          sets: 3,
          reps: "10–12",
          notes: { bg: "Наклонена пейка, лактите остават назад.", en: "Incline bench, elbows stay back." },
          steps: {
            bg: [
              "Седни на наклонена пейка (~45–60°), ръцете висят надолу, длани напред.",
              "Дръж лактите неподвижни и назад, сгъни дъмбелите нагоре.",
              "Стисни бицепса горе за кратко.",
              "Спусни бавно до пълно изпъване на ръцете.",
            ],
            en: [
              "Sit on an incline bench (~45–60°), arms hanging down, palms forward.",
              "Keep the elbows fixed and back, curl the dumbbells up.",
              "Squeeze the biceps at the top briefly.",
              "Lower slowly to a full arm extension.",
            ],
          },
          img: "",
        },
        {
          id: "u1e6",
          muscle: "triceps",
          exdb: "Lying_Dumbbell_Tricep_Extension",
          name: { bg: "Черепотрошач с дъмбели от лег", en: "Lying Dumbbell Skull Crusher" },
          sets: 3,
          reps: "10–12",
          notes: { bg: "От лег, сгъваш само в лактите.", en: "Lying, bend only at the elbows." },
          steps: {
            bg: [
              "Легни по гръб, дъмбелите изпънати над раменете, длани една срещу друга.",
              "Дръж лактите неподвижни и спускай дъмбелите към челото/ушите, сгъвайки само лактите.",
              "Спри точно преди да докоснеш главата.",
              "Изпъни ръцете обратно нагоре със стискане на трицепса.",
            ],
            en: [
              "Lie on your back, dumbbells extended over the shoulders, palms facing each other.",
              "Keep the elbows fixed and lower the dumbbells toward the forehead/ears, bending only the elbows.",
              "Stop just before touching your head.",
              "Extend the arms back up, squeezing the triceps.",
            ],
          },
          img: "",
        },
      ],
    },
    {
      id: "lowerA",
      icon: "🦵",
      name: { bg: "Ден 2: Долна А", en: "Day 2: Lower A" },
      focus: { bg: "Фокус: Квадрицепс", en: "Focus: Quadriceps" },
      exercises: [
        {
          id: "l1e1",
          muscle: "quads",
          exdb: "Dumbbell_Squat",
          name: { bg: "Клек с 2 дъмбела", en: "Dumbbell Squat" },
          sets: 4,
          reps: "8–10",
          notes: { bg: "Дъмбелите на раменете (Front) или до тялото.", en: "Dumbbells at shoulders (front) or at sides." },
          steps: {
            bg: [
              "Застани с дъмбели на раменете или до тялото, стъпала на ширина рамене.",
              "Дръж гърдите изправени и гледай напред, коремът стегнат.",
              "Клекни надолу, като буташ таза назад, бедрата поне до паралел.",
              "Избутай през петите нагоре до изправяне и повтори.",
            ],
            en: [
              "Stand with dumbbells at the shoulders or at the sides, feet shoulder-width apart.",
              "Keep the chest up and look forward, core braced.",
              "Squat down, pushing the hips back, thighs at least to parallel.",
              "Drive up through the heels to standing and repeat.",
            ],
          },
          img: "",
        },
        {
          id: "l1e2",
          muscle: "quads",
          exdb: "Split_Squat_with_Dumbbells",
          name: { bg: "Български клек", en: "Bulgarian Split Squat" },
          sets: 3,
          reps: "8–10 / крак",
          notes: { bg: "Дръж дъмбелите по 10 кг или повече.", en: "Hold 10 kg dumbbells or more." },
          steps: {
            bg: [
              "Стъпи с единия крак напред, задният крак опрян на пейка зад теб.",
              "Дръж дъмбелите до тялото, торсът леко наклонен напред.",
              "Спусни се надолу, докато предното бедро стигне паралел, коляното над глезена.",
              "Избутай през петата на предния крак нагоре; завърши сетовете и смени крака.",
            ],
            en: [
              "Step one foot forward, the rear foot resting on a bench behind you.",
              "Hold dumbbells at your sides, torso leaning slightly forward.",
              "Lower down until the front thigh reaches parallel, knee over the ankle.",
              "Drive up through the front heel; finish the sets and switch legs.",
            ],
          },
          img: "",
        },
        {
          id: "l1e3",
          muscle: "glutes",
          name: { bg: "Глутеус мост на пейка", en: "Bench Hip Thrust" },
          sets: 4,
          reps: "12–15",
          notes: { bg: "1 тежък дъмбел на таза.", en: "1 heavy dumbbell on the hips." },
          steps: {
            bg: [
              "Опри горната част на гърба на пейка, дъмбел върху таза.",
              "Стъпалата на пода, на ширина рамене, колене свити.",
              "Избутай таза нагоре, докато тялото е права линия от рамене до колене.",
              "Стисни седалището горе за 1 сек и спусни контролирано.",
            ],
            en: [
              "Rest your upper back on a bench, a dumbbell over your hips.",
              "Feet on the floor, shoulder-width apart, knees bent.",
              "Drive the hips up until the body is a straight line from shoulders to knees.",
              "Squeeze the glutes at the top for 1 s and lower under control.",
            ],
          },
          img: "",
        },
        {
          id: "l1e4",
          muscle: "calves",
          exdb: "Dumbbell_Seated_One-Leg_Calf_Raise",
          name: { bg: "Повдигане за прасец на 1 крак", en: "Single-Leg Calf Raise" },
          sets: 4,
          reps: "15–20",
          notes: { bg: "Дръж дъмбел в ръката от страната на работещия крак.", en: "Hold a dumbbell on the working leg's side." },
          steps: {
            bg: [
              "Застани с пръстите на единия крак върху стъпало/ръб, петата увиснала.",
              "Дръж дъмбел в ръката от страната на работещия крак, другата ръка за баланс.",
              "Повдигни се максимално на пръсти, стискайки прасеца.",
              "Спусни бавно до дълбоко разтягане; завърши и смени крака.",
            ],
            en: [
              "Stand with the toes of one foot on a step/edge, the heel hanging off.",
              "Hold a dumbbell on the working leg's side, the other hand for balance.",
              "Rise up as high as possible onto the toes, squeezing the calf.",
              "Lower slowly to a deep stretch; finish and switch legs.",
            ],
          },
          img: "",
        },
        {
          id: "l1e5",
          muscle: "core",
          exdb: "Crunches",
          name: { bg: "Коремни преси / Повдигане крака", en: "Crunches / Leg Raises" },
          sets: 3,
          reps: { bg: "До отказ", en: "To failure" },
          notes: { bg: "Бавно и контролирано спускане.", en: "Slow, controlled lowering." },
          steps: {
            bg: [
              "Легни по гръб, ръцете зад главата или покрай тялото.",
              "За коремни преси: повдигни раменете от пода, като свиваш корема.",
              "За повдигане на крака: вдигай изпънати крака до 90°, таза леко от пода.",
              "Спускай бавно и контролирано, без да дърпаш с врата.",
            ],
            en: [
              "Lie on your back, hands behind the head or along the body.",
              "For crunches: lift the shoulders off the floor by contracting the abs.",
              "For leg raises: lift straight legs to 90°, hips slightly off the floor.",
              "Lower slowly and controlled, without pulling with the neck.",
            ],
          },
          img: "",
        },
      ],
    },
    {
      id: "upperB",
      icon: "🏋️",
      name: { bg: "Ден 3: Горна Б", en: "Day 3: Upper B" },
      focus: {
        bg: "Фокус: Рамена, вертикално дърпане + плътност",
        en: "Focus: Shoulders, vertical pull + density",
      },
      exercises: [
        {
          id: "u2e1",
          muscle: "shoulders",
          exdb: "Dumbbell_Shoulder_Press",
          name: { bg: "Раменни преси от сед", en: "Seated Shoulder Press" },
          sets: 4,
          reps: "8–10",
          notes: { bg: "Пейка на ~75°, стабилна опора на гърба.", en: "Bench at ~75°, stable back support." },
          steps: {
            bg: [
              "Седни на пейка с облегалка ~75°, дъмбели на нивото на раменете, длани напред.",
              "Стегни корема и дръж гърба опрян на облегалката.",
              "Избутай дъмбелите нагоре, докато почти се докоснат горе.",
              "Спусни контролирано до нивото на ушите и повтори.",
            ],
            en: [
              "Sit on a bench with the backrest at ~75°, dumbbells at shoulder level, palms forward.",
              "Brace the core and keep the back against the backrest.",
              "Press the dumbbells up until they almost touch at the top.",
              "Lower under control to ear level and repeat.",
            ],
          },
          img: "",
        },
        {
          id: "u2e2",
          muscle: "chest",
          exdb: "Dumbbell_Bench_Press",
          name: { bg: "Избутване от хоризонтален лег", en: "Flat Dumbbell Press" },
          sets: 4,
          reps: "8–10",
          notes: { bg: "Права лежанка (заменя задното рамо).", en: "Flat bench (replaces rear delts)." },
          steps: {
            bg: [
              "Легни по гръб на хоризонтална пейка, дъмбели на нивото на гърдите, длани напред.",
              "Стъпалата здраво на пода, плешките прибрани назад.",
              "Избутай дъмбелите нагоре до почти изпънати ръце.",
              "Спусни бавно до разтягане на гърдите и повтори.",
            ],
            en: [
              "Lie on a flat bench, dumbbells at chest level, palms forward.",
              "Feet firmly on the floor, shoulder blades pulled back.",
              "Press the dumbbells up to nearly straight arms.",
              "Lower slowly to a chest stretch and repeat.",
            ],
          },
          img: "",
        },
        {
          id: "u2e3",
          muscle: "back",
          exdb: "Straight-Arm_Dumbbell_Pullover",
          name: { bg: "Пуловър с 1 дъмбел", en: "Dumbbell Pullover" },
          sets: 3,
          reps: "10–12",
          notes: { bg: "Акцент на разтягането в гърба, лакти леко свити.", en: "Emphasize back stretch, elbows slightly bent." },
          steps: {
            bg: [
              "Легни по гръб, хвани 1 дъмбел с две ръце над гърдите, лакти леко свити.",
              "Спускай дъмбела по дъга назад зад главата, докато усетиш разтягане в гърба/гърдите.",
              "Дръж таза стабилен, без да извиваш кръста.",
              "Върни дъмбела над гърдите, като водиш с широкия гръб.",
            ],
            en: [
              "Lie on your back, hold one dumbbell with both hands over the chest, elbows slightly bent.",
              "Lower the dumbbell in an arc back behind your head until you feel a lat/chest stretch.",
              "Keep the hips stable, without arching the lower back.",
              "Return the dumbbell over the chest, leading with the lats.",
            ],
          },
          img: "",
        },
        {
          id: "u2e4",
          muscle: "back",
          exdb: "Dumbbell_Incline_Row",
          name: { bg: "Гребане с опора по гърди", en: "Chest-Supported Row" },
          sets: 3,
          reps: "10–12",
          notes: { bg: "Лягаш по корем на наклонената пейка, дърпаш 2 дъмбела.", en: "Lie prone on incline bench, pull 2 dumbbells." },
          steps: {
            bg: [
              "Нагласи наклонена пейка (~30°) и легни по корем с гърди на облегалката.",
              "Дръж по един дъмбел във всяка ръка, висящи надолу.",
              "Дръпни дъмбелите към кръста, като стискаш плешките.",
              "Спусни контролирано до пълно разтягане и повтори.",
            ],
            en: [
              "Set an incline bench (~30°) and lie prone with your chest on the pad.",
              "Hold a dumbbell in each hand, hanging down.",
              "Pull the dumbbells to your waist, squeezing the shoulder blades.",
              "Lower under control to a full stretch and repeat.",
            ],
          },
          img: "",
        },
        {
          id: "u2e5",
          muscle: "biceps",
          exdb: "Hammer_Curls",
          name: { bg: "Чуково сгъване (Hammer curl)", en: "Hammer Curl" },
          sets: 3,
          reps: "10–12",
          notes: { bg: "От стоеж или сед, неутрален хват.", en: "Standing or seated, neutral grip." },
          steps: {
            bg: [
              "Застани или седни с дъмбели до тялото, длани обърнати към тялото (неутрален хват).",
              "Дръж лактите прибрани и неподвижни.",
              "Сгъни дъмбелите нагоре, запазвайки неутралния хват.",
              "Стисни горе и спусни бавно до изпъване.",
            ],
            en: [
              "Stand or sit with dumbbells at your sides, palms facing in (neutral grip).",
              "Keep the elbows tucked and fixed.",
              "Curl the dumbbells up, keeping the neutral grip.",
              "Squeeze at the top and lower slowly to extension.",
            ],
          },
          img: "",
        },
        {
          id: "u2e6",
          muscle: "triceps",
          exdb: "Seated_Triceps_Press",
          name: { bg: "Разгъване над глава (Трицепс)", en: "Overhead Triceps Extension" },
          sets: 3,
          reps: "12–15",
          notes: { bg: "С 1 тежък дъмбел държан с две ръце.", en: "1 heavy dumbbell held with both hands." },
          steps: {
            bg: [
              "Хвани 1 дъмбел с две ръце и го вдигни над главата, ръцете изпънати.",
              "Дръж лактите близо до главата и сочещи напред.",
              "Спусни дъмбела зад главата, като сгъваш само лактите.",
              "Изпъни ръцете обратно нагоре със стискане на трицепса.",
            ],
            en: [
              "Hold one dumbbell with both hands and raise it overhead, arms extended.",
              "Keep the elbows close to the head and pointing forward.",
              "Lower the dumbbell behind the head, bending only the elbows.",
              "Extend the arms back up, squeezing the triceps.",
            ],
          },
          img: "",
        },
      ],
    },
    {
      id: "lowerB",
      icon: "🦵",
      name: { bg: "Ден 4: Долна Б", en: "Day 4: Lower B" },
      focus: {
        bg: "Фокус: Задно бедро и седалище",
        en: "Focus: Hamstrings & glutes",
      },
      exercises: [
        {
          id: "l2e1",
          muscle: "hamstrings",
          exdb: "Stiff-Legged_Dumbbell_Deadlift",
          name: { bg: "Румънска тяга с дъмбели", en: "Romanian Deadlift" },
          sets: 4,
          reps: "8–10",
          notes: { bg: "Бутай таза максимално назад, не клякай.", en: "Push hips back, don't squat." },
          steps: {
            bg: [
              "Застани прав с дъмбели пред бедрата, колене съвсем леко свити.",
              "Бутай таза максимално назад, спускайки дъмбелите покрай краката.",
              "Дръж гърба прав, докато усетиш разтягане в задното бедро.",
              "Избутай таза напред до изправяне, стискайки седалището.",
            ],
            en: [
              "Stand tall with dumbbells in front of the thighs, knees only slightly bent.",
              "Push the hips back as far as possible, lowering the dumbbells along the legs.",
              "Keep the back flat until you feel a hamstring stretch.",
              "Drive the hips forward to standing, squeezing the glutes.",
            ],
          },
          img: "",
        },
        {
          id: "l2e2",
          muscle: "glutes",
          exdb: "Dumbbell_Lunges",
          name: { bg: "Ходещи напади (или на място)", en: "Walking Lunges" },
          sets: 4,
          reps: "10–12 / крак",
          notes: { bg: "Дълга крачка = повече глутеус; къса = квадрицепс.", en: "Long stride = more glutes; short = quads." },
          steps: {
            bg: [
              "Застани прав с дъмбели до тялото.",
              "Направи дълга крачка напред и спусни задното коляно към пода.",
              "Избутай през петата на предния крак и пристъпи с другия крак напред.",
              "Продължи да редуваш краката за зададените повторения.",
            ],
            en: [
              "Stand tall with dumbbells at your sides.",
              "Take a long step forward and lower the back knee toward the floor.",
              "Drive through the front heel and step forward with the other leg.",
              "Keep alternating legs for the target reps.",
            ],
          },
          img: "",
        },
        {
          id: "l2e3",
          muscle: "glutes",
          exdb: "Plie_Dumbbell_Squat",
          name: { bg: "Сумо клек с 1 дъмбел", en: "Sumo Squat" },
          sets: 3,
          reps: "10–12",
          notes: { bg: "Широк разкрач, държиш тежкия дъмбел между краката.", en: "Wide stance, heavy dumbbell between the legs." },
          steps: {
            bg: [
              "Застани с широк разкрач, пръстите леко навън, държиш 1 дъмбел между краката.",
              "Дръж гърдите изправени и коремът стегнат.",
              "Клекни надолу, коленете следват посоката на пръстите, до паралел.",
              "Избутай през петите нагоре, стискайки седалището.",
            ],
            en: [
              "Stand with a wide stance, toes slightly out, holding one dumbbell between the legs.",
              "Keep the chest up and the core braced.",
              "Squat down, knees tracking over the toes, to parallel.",
              "Drive up through the heels, squeezing the glutes.",
            ],
          },
          img: "",
        },
        {
          id: "l2e4",
          muscle: "hamstrings",
          name: { bg: "Сгъване за задно бедро от лег", en: "Lying Leg Curl" },
          sets: 3,
          reps: "12–15",
          notes: { bg: "Легнал по корем на пейката, дъмбел между ходилата.", en: "Lie prone on bench, dumbbell between the feet." },
          steps: {
            bg: [
              "Легни по корем на пейка, дъмбел захванат между ходилата.",
              "Дръж бедрата притиснати към пейката.",
              "Сгъни краката, повдигайки дъмбела към седалището.",
              "Спусни бавно и контролирано до изпъване на краката.",
            ],
            en: [
              "Lie prone on a bench, a dumbbell held between the feet.",
              "Keep the thighs pressed into the bench.",
              "Curl the legs, lifting the dumbbell toward the glutes.",
              "Lower slowly and controlled to full leg extension.",
            ],
          },
          img: "",
        },
        {
          id: "l2e5",
          muscle: "core",
          exdb: "Plank",
          name: { bg: "Планк (с тежест, ако е лесно)", en: "Plank (weighted if easy)" },
          sets: 3,
          reps: "45–60 сек",
          notes: { bg: "Може да сложиш 10 кг дъмбел на гърба си.", en: "You can place a 10 kg dumbbell on your back." },
          steps: {
            bg: [
              "Опри лактите и пръстите на краката на пода, лактите под раменете.",
              "Стегни корема и седалището, тялото в права линия.",
              "Дръж позицията, без да увисваш в кръста или да вдигаш таза.",
              "Дишай равномерно и задръж за зададеното време.",
            ],
            en: [
              "Place the elbows and toes on the floor, elbows under the shoulders.",
              "Brace the core and glutes, body in a straight line.",
              "Hold the position without sagging the lower back or raising the hips.",
              "Breathe steadily and hold for the target time.",
            ],
          },
          img: "",
        },
      ],
    },
  ],
};
